export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const POST_FORGOT_PASSWORD = "POST_FORGOT_PASSWORD";
export const POST_FORGOT_PASSWORD_SUCCESS = "POST_FORGOT_PASSWORD_SUCCESS";
export const POST_FORGOT_PASSWORD_ERROR = "POST_FORGOT_PASSWORD_ERROR";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_PROFILE_INFO = "LOGIN/GET_PROFILE_INFO";
export const GET_PROFILE_INFO_SUCCESS = "LOGIN/GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_ERROR = "LOGIN/GET_PROFILE_INFO_ERROR";

export const GET_CLOCK_DATA = "LOGIN/GET_CLOCK_DATA";
export const GET_CLOCK_DATA_SUCCESS = "LOGIN/GET_CLOCK_DATA_SUCCESS";

export const GET_WEEK_DATA = "LOGIN/GET_WEEK_DATA";
export const GET_WEEK_DATA_SUCCESS = "LOGIN/GET_WEEK_DATA_SUCCESS";

export const SET_FILE_UPLOAD_DATA = "LOGIN/SET_FILE_UPLOAD_DATA";

export const UPDATE_PROFILE_PICTURE = "LOGIN/UPDATE_PROFILE_PICTURE";
export const UPDATE_CREDIT_AMOUNT = "LOGIN/UPDATE_CREDIT_AMOUNT";

export const TOGGLE_ADD_CREDIT_MODAL = "LOGIN/TOGGLE_ADD_CREDIT_MODAL";

export const CLEAR_LOGIN_MESSAGE = "CLEAR_LOGIN_MESSAGE";
