export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const CLEAR_REGISTER_MESSAGE = "CLEAR_REGISTER_MESSAGE";
