export const GET_RATED_VENDOR = "USER/DASHBOARD_PAGE/GET_RATED_VENDOR";
export const GET_RATED_VENDOR_SUCCESS =
  "USER/DASHBOARD_PAGE/GET_RATED_VENDOR_SUCCESS";
export const GET_RATED_VENDOR_ERROR =
  "USER/DASHBOARD_PAGE/GET_RATED_VENDOR_ERROR";

export const GET_NEARBY_VENDOR = "USER/DASHBOARD_PAGE/GET_NEARBY_VENDOR";
export const GET_NEARBY_VENDOR_SUCCESS =
  "USER/DASHBOARD_PAGE/GET_NEARBY_VENDOR_SUCCESS";
export const GET_NEARBY_VENDOR_ERROR =
  "USER/DASHBOARD_PAGE/GET_NEARBY_VENDOR_ERROR";

export const CLEAR_DASHBOARD_PAGE = "USER/DASHBOARD_PAGE/CLEAR_DASHBOARD_PAGE";
