export const GET_USER_LIST = "ADMIN/PEOPLE_USER_PAGE/GET_USER_LIST";
export const GET_USER_LIST_SUCCESS =
  "ADMIN/PEOPLE_USER_PAGE/GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_ERROR = "ADMIN/PEOPLE_USER_PAGE/GET_USER_LIST_ERROR";

export const CLEAR_USER_LIST_DATA =
  "ADMIN/PEOPLE_USER_PAGE/CLEAR_USER_LIST_DATA";
