export const GET_GLOBAL_SEARCH = "GLOBAL_SEARCH/GET_GLOBAL_SEARCH";
export const GET_GLOBAL_SEARCH_SUCCESS =
  "GLOBAL_SEARCH/GET_GLOBAL_SEARCH_SUCCESS";
export const GET_GLOBAL_SEARCH_ERROR = "GLOBAL_SEARCH/GET_GLOBAL_SEARCH_ERROR";

export const CLEAR_GLOBAL_SEARCH = "GLOBAL_SEARCH/CLEAR_GLOBAL_SEARCH";
