export const POST_PAYMENT_INTENT = "PAYMENT_FORM/POST_PAYMENT_INTENT";
export const POST_PAYMENT_INTENT_SUCCESS =
  "PAYMENT_FORM/POST_PAYMENT_INTENT_SUCCESS";
export const POST_PAYMENT_INTENT_ERROR =
  "PAYMENT_FORM/POST_PAYMENT_INTENT_ERROR";

export const CLEAR_MESSAGE = "PAYMENT_FORM/CLEAR_MESSAGE";
