export const GET_CREDIT_HISTORY = "CREDIT_PAGE/GET_CREDIT_HISTORY";
export const GET_CREDIT_HISTORY_SUCCESS =
  "CREDIT_PAGE/GET_CREDIT_HISTORY_SUCCESS";
export const GET_CREDIT_HISTORY_ERROR = "CREDIT_PAGE/GET_CREDIT_HISTORY_ERROR";

export const CLEAR_CREDIT_HISTORY = "CREDIT_PAGE/CLEAR_CREDIT_HISTORY";
