export const GET_DASHBOARD_INFO = "ADMIN/DASHBOARD_PAGE/GET_DASHBOARD_INFO";
export const GET_DASHBOARD_INFO_SUCCESS =
  "ADMIN/DASHBOARD_PAGE/GET_DASHBOARD_INFO_SUCCESS";
export const GET_DASHBOARD_INFO_ERROR =
  "ADMIN/DASHBOARD_PAGE/GET_DASHBOARD_INFO_ERROR";

export const GET_CURRENT_BOOKING = "ADMIN/DASHBOARD_PAGE/GET_CURRENT_BOOKING";
export const GET_CURRENT_BOOKING_SUCCESS =
  "ADMIN/DASHBOARD_PAGE/GET_CURRENT_BOOKING_SUCCESS";
export const GET_CURRENT_BOOKING_ERROR =
  "ADMIN/DASHBOARD_PAGE/GET_CURRENT_BOOKING_ERROR";

export const CLEAR_DASHBOARD_PAGE = "ADMIN/DASHBOARD_PAGE/CLEAR_DASHBOARD_PAGE";
