export const POST_PROFILE_INFO = "BASIC_INFORMATION/POST_PROFILE_INFO";
export const POST_PROFILE_INFO_SUCCESS =
  "BASIC_INFORMATION/POST_PROFILE_INFO_SUCCESS";
export const POST_PROFILE_INFO_ERROR =
  "BASIC_INFORMATION/POST_PROFILE_INFO_ERROR";

export const POST_CHANGE_EMAIL = "BASIC_INFORMATION/POST_CHANGE_EMAIL";
export const POST_CHANGE_EMAIL_SUCCESS =
  "BASIC_INFORMATION/POST_CHANGE_EMAIL_SUCCESS";
export const POST_CHANGE_EMAIL_ERROR =
  "BASIC_INFORMATION/POST_CHANGE_EMAIL_ERROR";

export const CLEAR_MESSAGE = "BASIC_INFORMATION/CLEAR_MESSAGE";
