export const GET_BOOKING_DETAIL = "USER/BOOKING_DETAIL_PAGE/GET_BOOKING_DETAIL";
export const GET_BOOKING_DETAIL_SUCCESS =
  "USER/BOOKING_DETAIL_PAGE/GET_BOOKING_DETAIL_SUCCESS";
export const GET_BOOKING_DETAIL_ERROR =
  "USER/BOOKING_DETAIL_PAGE/GET_BOOKING_DETAIL_ERROR";

export const REMOVE_BOOKING = "USER/BOOKING_DETAIL_PAGE/REMOVE_BOOKING";
export const REMOVE_BOOKING_SUCCESS =
  "USER/BOOKING_DETAIL_PAGE/REMOVE_BOOKING_SUCCESS";
export const REMOVE_BOOKING_ERROR =
  "USER/BOOKING_DETAIL_PAGE/REMOVE_BOOKING_ERROR";

export const CLEAR_POST_DATA = "USER/BOOKING_DETAIL_PAGE/CLEAR_POST_DATA";
