export const POST_PROFILE_INFO = "ADMIN/ADD_USER/POST_PROFILE_INFO";
export const POST_PROFILE_INFO_SUCCESS =
  "ADMIN/ADD_USER/POST_PROFILE_INFO_SUCCESS";
export const POST_PROFILE_INFO_ERROR = "ADMIN/ADD_USER/POST_PROFILE_INFO_ERROR";

export const GET_PROFILE_INFO = "ADMIN/ADD_USER/GET_PROFILE_INFO";
export const GET_PROFILE_INFO_SUCCESS =
  "ADMIN/ADD_USER/GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_ERROR = "ADMIN/ADD_USER/GET_PROFILE_INFO_ERROR";

export const CLEAR_MESSAGE = "ADMIN/ADD_USER/CLEAR_MESSAGE";
