export const GET_VENDOR_LIST = "USER/VENDOR_LIST_PAGE/GET_VENDOR_LIST";
export const GET_VENDOR_LIST_SUCCESS =
  "USER/VENDOR_LIST_PAGE/GET_VENDOR_LIST_SUCCESS";
export const GET_VENDOR_LIST_ERROR =
  "USER/VENDOR_LIST_PAGE/GET_VENDOR_LIST_ERROR";

export const CLEAR_VENDOR_DATA = "USER/VENDOR_LIST_PAGE/CLEAR_VENDOR_DATA";
