export const POST_PROFILE_PICTURE = "IMAGE_FIELD/POST_PROFILE_PICTURE";
export const POST_PROFILE_PICTURE_SUCCESS = "IMAGE_FIELD/POST_PROFILE_PICTURE_SUCCESS";
export const POST_PROFILE_PICTURE_ERROR = "IMAGE_FIELD/POST_PROFILE_PICTURE_ERROR";

export const CLEAR_MESSAGE = "IMAGE_FIELD/CLEAR_MESSAGE";
