export const POST_PROFILE_INFO = "ADMIN/ADD_VENDOR/POST_PROFILE_INFO";
export const POST_PROFILE_INFO_SUCCESS =
  "ADMIN/ADD_VENDOR/POST_PROFILE_INFO_SUCCESS";
export const POST_PROFILE_INFO_ERROR =
  "ADMIN/ADD_VENDOR/POST_PROFILE_INFO_ERROR";

export const GET_PROFILE_INFO = "ADMIN/ADD_VENDOR/GET_PROFILE_INFO";
export const GET_PROFILE_INFO_SUCCESS =
  "ADMIN/ADD_VENDOR/GET_PROFILE_INFO_SUCCESS";
export const GET_PROFILE_INFO_ERROR = "ADMIN/ADD_VENDOR/GET_PROFILE_INFO_ERROR";

export const UPDATE_USER_PHOTO = "ADMIN/ADD_VENDOR/UPDATE_USER_PHOTO";
export const CLEAR_USER_INFO = "ADMIN/ADD_VENDOR/CLEAR_USER_INFO";

export const CLEAR_MESSAGE = "ADMIN/ADD_VENDOR/CLEAR_MESSAGE";
