export const SET_PASSWORD = "SET_PASSWORD";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";

export const CLEAR_SET_PASSWORD_MESSAGE = "CLEAR_SET_PASSWORD_MESSAGE";
