export const POST_PROFILE_INFO = "BASIC_INFORMATION/POST_PROFILE_INFO";
export const POST_PROFILE_INFO_SUCCESS =
  "BASIC_INFORMATION/POST_PROFILE_INFO_SUCCESS";
export const POST_PROFILE_INFO_ERROR =
  "BASIC_INFORMATION/POST_PROFILE_INFO_ERROR";

export const CLEAR_MESSAGE = "BASIC_INFORMATION/CLEAR_MESSAGE";
